version: '3'

services:
  bot:
    build: .
    container_name: url-uploader-pro
    restart: unless-stopped
    volumes:
      - ./downloads:/app/downloads
      - ./.env:/app/.env
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Kolkata
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
